# Generated by Django 5.1.2 on 2024-10-13 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated']},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='upadted',
            new_name='updated',
        ),
    ]
